config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :templates do
      member do
        post :clone
      end
    end
    
    # delete 'templates/:template_id/template_frames/:id', to: "template_frames#destroy", as: :template_frame

    resources :products do 
      member do 
        post :get_taxons
      end
    end
  end

end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  belongs_to :template, optional: :true
end

app/models/spree/template.rb
class Spree::Template < Spree::Base

  attr_accessor :background

  acts_as_paranoid
  include Spree::ParanoiaDeprecations


  include Discard::Model
  self.discard_column = :deleted_at

  has_many :products

  validates_presence_of :name, :width, :height
  validates :width, :height, numericality: { greater_than: 0 }

end

app/controllers/spree/admin/templates_controller.rb
module Spree
  module Admin
    class TemplatesController < ResourceController

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def new
        @template = Spree::Template.new
      end

      def create
        @template = Spree::Template.new(permitted_resource_params)
        invoke_callbacks(:create, :before)
        if @template.save
          invoke_callbacks(:create, :after)
          flash[:success] = Spree.t('template.successfully_created')
          redirect_to edit_admin_template_path(@template)
        else
          invoke_callbacks(:create, :fails)
          respond_with(@template)
        end
      end

      def show
        redirect_to action: :edit
      end

      def edit
      end

      def update
        if @object.update_attributes(permitted_resource_params)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to spree.edit_admin_template_path(@template) }
            format.js   { render layout: false }
          end
        else
          respond_with(@object)
        end
      end

      def destroy
        @template = Spree::Template.find(params[:id])
        if @template.products.present?
          @template.products.update(template_id: nil)
        end
        @template.discard
        flash[:success] = t('spree.notice_messages.template_deleted')
        respond_with(@template) do |format|
          format.html { redirect_to collection_url }
          format.js { render_js_for_destroy }
        end
      end

      private

        def find_resource
          Spree::Template.with_deleted.find(params[:id])
        end

        def collection
          return @collection if @collection
          params[:q] ||= {}
          params[:q][:s] ||= "name asc"
          @search = super.ransack(params[:q])
          @collection = @search.result.
                order(id: :asc).
                page(params[:page]).per(params[:per_page])
        end
    end
  end
end

app/helpers/spree/templates_helper.rb
module Spree::TemplatesHelper
end

app/views/spree/admin/shared/_on_demand_settings_sub_menu.html.erb
<ul class="admin-subnav" data-hook="admin_on_demand_sub_tabs">
  <% if can? :admin, Spree::Template %>
    <%= tab :templates, match_path: '/templates' %>
  <% end %>
</ul>

app/views/spree/admin/templates/_form.html.erb
<div class="form-group" data-hook="admin_template_form_name">
  <%= f.field_container :name do %>
    <%= f.label :template_name, class: 'required' %>
    <%= f.text_field :name, class: 'fullwidth title', required: true %>
    <%= f.error_message_on :name %>
  <% end %>
</div>

<div class="form-group" data-hook="admin_template_form_description">
  <%= f.field_container :description do %>
    <%= f.label :template_description %>
    <%= f.text_area :description, class: 'fullwidth title form-control', rows: "3" %>
    <%= f.error_message_on :description %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group" data-hook="admin_template_form_width">
      <%= f.field_container :width do %>
        <%= f.label :template_width , class: 'required' %>
        <%= f.number_field :width, data: {range: 'width'}, required: true, class: 'range-field' %>
        <%= f.error_message_on :width %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group" data-hook="admin_template_form_height">
      <%= f.field_container :height do %>
        <%= f.label :template_height, class: 'required' %>
        <%= f.number_field :height, data: {range: 'height'}, required: true, class: 'range-field' %>
        <%= f.error_message_on :height %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group" data-hook="admin_template_form_edges">
      <%= f.field_container :resolution do %>
        <%= f.label :template_resolution do %>
          Template Resolution<span class="valueShow"></span>
        <% end %>
        <%= f.range_field :resolution, data: {range: 'resolution'}, min: '0', max: '300' %>
        <%= f.error_message_on :resolution %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group" data-hook="admin_template_form_edges">
      <%= f.field_container :edges do %>
        <%= f.label :template_rounded_edges do %>
          Template Rounded Edges<span class="valueShow"></span>
        <% end %>
        <% max_edge = @template.present? ? @template.width : '400' %>
        <%= f.range_field :edges, data: {range: 'radius'}, min: '0', max: max_edge %>
        <%= f.error_message_on :edges %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group hide-margin" data-hook="admin_template_form_number_of_images">
      <%= f.field_container :background do %>
        <%= f.label :background %><br>
        <label class="radio-inline">
          <%= f.radio_button :background, 'background_image' %><%= I18n.t('spree.template.background_image') %>
        </label>
        <label class="radio-inline">
          <%= f.radio_button :background, 'background_color' %><%= I18n.t('spree.template.background_color') %>
        </label>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group" data-hook="admin_template_form_number_of_images">
      <%= f.field_container :number_of_images do %>
        <%= f.label :add_images %>
        <%= f.number_field :number_of_images, class: 'fullwidth title form-control', min: '0', max: '20' %>
        <%= f.error_message_on :number_of_images %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group" data-hook="admin_template_form_number_of_images">
      <%= f.field_container :number_of_text_boxes do %>
        <%= f.label :add_texts %>
        <%= f.number_field :number_of_text_boxes, class: 'fullwidth title form-control', min: '0', max: '20' %>
        <%= f.error_message_on :number_of_text_boxes %>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/templates/_preview_shape.html.erb
<% images_number_range = images_range(@template) %>
<% if number_of_images?(@template) %>
  <% images_number_range.each do |img_number| %>
    <div class="preview-inner-img" data-layer="layer-<%= img_number %>"></div>
  <% end %>
<% end %>

<% text_boxes_range = textboxes_range(@template) %>
<% if number_of_text_boxes?(@template) %>
  <% text_boxes_range.each do |text_number| %>
    <div class="preview-inner-img preview-inner-text" data-layer="layer-text-<%= text_number %>"></div>
  <% end %>
<% end %>

app/views/spree/admin/templates/edit.html.erb
<% admin_layout "full-width" %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Template) %>
    <li id="new_template_link">
      <%= button_link_to t('spree.new_template'), new_object_url, { id: 'admin_new_template' } %>
    </li>
  <% end %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @template } %>

<% admin_breadcrumb(t('spree.template_details')) %>

<div data-hook="admin_template_form_fields">
  <main class="gxp-admin">
    <div class="row">
      <div class="container col-12 text-left">
        <%= form_for [:admin, @template] do |f| %>
          <fieldset class="no-border-top no-border-bottom sticky-container">
            <div class="zoom-inout-scale" data-zoom-scale="<%= (500.to_f / @template.width.to_f).round(1) %>" data-zoom-change="0.05">
              <button class="btn" data-zoom="negative">
                <i class="fa fa-minus"></i>
              </button>
              <button class="btn" data-zoom="positive">
                <i class="fa fa-plus"></i>
              </button>
              <div class="current-size">
                <%= t('spree.scale.label') %>: <%= t('spree.scale.original') %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-8"><!-- sticky-static -->
                <div class="overflow-container">
                  <div class="template-preview">
                    <h2><%= t(:'spree.template.template_preview') %></h2>
                    <div class="scale-parent">
                      <div class="preview-shape">
                          <!-- preview shape of images and text -->
                          <%#= render partial: 'preview_shape' %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-content form-content-scroll">
                  <%= render partial: 'form', locals: { f: f } %>
                </div>
              </div>
            </div>
          </fieldset>

          <% if can?(:update, @template) %>
            <fieldset class="no-border-top">
              <%= render partial: 'spree/admin/shared/edit_resource_links' %>
            </fieldset>
          <% end %>
        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/spree/admin/templates/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::Template)) %>

<% content_for :page_actions do %>
  <li id="new_template_link">
    <%= button_link_to Spree.t(:new_template), new_admin_template_path, { :id => 'new_admin_template' } %>
  </li>
<% end if can?(:create, Spree::Template) %>

<div id="new_template_wrapper" data-hook></div>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_templates">
    <thead>
      <tr data-hook="admin_templates_index_headers">
        <th><%= sort_link @search, :name, Spree::Template.human_attribute_name(:name), { default_order: "desc" }, {title: 'admin_templates_listing_name_title'} %></th>
        <th><%= Spree::Template.human_attribute_name(:description) %></th>
        <th><%= Spree::Template.human_attribute_name(:width) %></th>
        <th><%= Spree::Template.human_attribute_name(:height) %></th>
        <th><%= Spree::Template.human_attribute_name(:edges) %></th>
        <th><%= Spree::Template.human_attribute_name(:total_images) %></th>
        <th><%= Spree::Template.human_attribute_name(:total_textboxes) %></th>
        <th data-hook="admin_templates_index_header_actions" class="actions"><%= Spree::Template.human_attribute_name(:actions) %></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |template| %>
          <tr <%= "style='color: red;'" if template.deleted? %> id="<%= spree_dom_id template %>" data-hook="admin_templates_index_rows">
            <td><%= link_to template.try(:name), edit_admin_template_path(template) %></td>
            <td><%= template.description %></td>
            <td><%= template.width %></td>
            <td><%= template.height %></td>
            <td><%= template.edges %></td>
            <td class="text-center"><%= template.number_of_images %></td>
            <td class="text-center"><%= template.number_of_text_boxes %></td>
            <td class="actions" data-hook="admin_templates_index_row_actions">
              <%= link_to_edit template, no_text: true, class: 'edit' if can?(:edit, template) && !template.deleted? %>
              &nbsp;
              <%= link_to_delete template, no_text: true if can?(:delete, template) && !template.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
 <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                  resource: Spree::Template,
                  new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/templates/new.html.erb
<% admin_breadcrumb link_to(plural_resource_name(Spree::Template), spree.admin_templates_path) %>

<% admin_breadcrumb t('spree.new_template') %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @template } %>

<div data-hook="admin_template_form_fields">
  <main class="gxp-admin">
    <div class="">
      <div class="container">
        <%= form_for [:admin, @template], method: :post, url: admin_templates_path do |f| %>
          <fieldset data-hook="new_template" class="no-border-top no-border-bottom sticky-container">
            <div class="zoom-inout-scale" data-zoom-scale="0.8" data-zoom-change="0.01">
              <button class="btn" data-zoom="negative">
                <i class="fa fa-minus"></i>
              </button>
              <button class="btn" data-zoom="positive">
                <i class="fa fa-plus"></i>
              </button>
              <div class="current-size">
                <%= t('spree.scale.label') %>: <%= t('spree.scale.original') %>
              </div>
            </div>
            <legend align="center"><%= t('spree.new_template') %></legend>
            <div class="row">
              <div class="col-md-7"> <!-- sticky-static -->
                <div class="overflow-container">
                  <div class="template-preview">
                    <h2><%= t(:'spree.template.template_preview') %></h2>
                    
                  </div>
                </div>
              </div>
              <div class="col-md-5">
                <div class="form-content form-content-scroll">
                  <%= render partial: 'form', locals: { f: f } %>
                </div>
              </div>
            </div>
          </fieldset>
          <fieldset class="no-border-top">
            <%= render partial: 'spree/admin/shared/new_resource_links' %>
          </fieldset>
        <% end %>
      </div>
    </div>
  </main>
</div>